Switch from docker-compose to docker
Use ./run instead of the docker-compose command in order to avoid the error:

ERROR: Service 'mender-deployments' depends on service 'storage-proxy' which is undefined.

Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
Signed-off-by: KopterMax <58376641+koptermax@users.noreply.github.com>