Switch from docker-compose to ./run
Use ./run instead of the docker-compose command in order to avoid the error:

ERROR: Service 'mender-deployments' depends on service 'storage-proxy' which is undefined.