fix: docs: Use DISTRO_FEATURES_OPTED_OUT
Replace variable DISTRO_FEATURES_BACKFILL_CONSIDERED with variable
DISTRO_FEATURES_OPTED_OUT following the changes in Yocto release
Wrynose. Fixes:

ERROR: Variable DISTRO_FEATURES_BACKFILL_CONSIDERED has been
renamed to DISTRO_FEATURES_OPTED_OUT

This work was sponsored by GOVCERT.LU.

Changelog: Use DISTRO_FEATURES_OPTED_OUT
Ticket: None

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>